### ISSUE TITLE
Error while creating html from pastes. 

### ISSUE THREAD

**Issue by upgoingstar** [upgoingstar/datasploit#2]
Getting following error while making html from pastes. 

Traceback (most recent call last):
  File "domainOsint.py", line 499, in <module>
    main()
  File "domainOsint.py", line 470, in main
    do_everything(domain, output)
  File "domainOsint.py", line 185, in do_everything
    for y in results['items']:
TypeError: list indices must be integers, not str

@KunalAggarwal Please check.

**Comment by KunalAggarwal** [comment]
@upgoingstar Fixed in latest Pull Request. Check now.
